version: "3"
services:
  swoole:
    build:
      context: .
    depends_on:
      - finance_db
    restart: always
    ports:
      - "8001:80"
    environment:
      - SWOOLE_HTTP_HOST=0.0.0.0
      - SWOOLE_HTTP_PORT=80
      - DATABASE_URL=postgres://postgres:postgres@finance_db:5432/finance
      - APP_ENV=local
      - APP_DEBUG=true
      - CORPORATE=http://localhost:8080

  finance_db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    volumes:
      - data:/var/lib/postgresql/financedata

volumes:
  data:
